apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: {{ .Values.backend.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30087
      {{- end }}
  type: {{ .Values.service.type }}