apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  kantra-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: internship
    server: https://kubernetes.default.svc # ken bch namlou apply manual al cluster nktbou   https://kubernetes.default.svc
  source:
    path: kantra-app # you chould provide the folder in the git repo
    repoURL: "https://github.com/06061991/argocd.git" # the url of the github repository
    targetRevision: HEAD # the branch of the github repository.We can use Head or a specific version
  syncPolicy:
    automated: {} # This will detect changes automatically from the repository
    syncOptions:
      - CreateNamespace=true